- README.rst
* Point to working Travis URL
* fix Inline code examples
> Fixing README.rst

- adafruit_io/adafruit_io.py
- docs/api.rst
- docs/conf.py
* Added explicit check for the `wifi` kwarg against `adafruit_esp32spi_wifimanager.ESPSPI_WiFiManager` to make sure it's it's an instance of _WiFiManager, not something else accidentally passed in
* Changed api.rst to reflect directory structure
* Changed `_compose_path` to a more readable path.
Changes requested per: https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/pull/1
> Fixes per sommersoft's review

- adafruit_io/adafruit_io.py
- docs/conf.py
Removing 
`        if isinstance(wifi_manager, adafruit_esp32spi_wifimanager.ESPSPI_WiFiManager):	`
in favor of 
`        if ('ESPSPI_WiFiManager' in wifi_type or 'ESPAT_WiFiManager' in wifi_type):`
The library won't need to import `adafruit_esp32spi_wifimanager`, and this'll add more flexibility for future types of WiFiManager classes (such as the `ESPAT_WiFiManager` @jerryneedell  is working on. I've added support for that) 
* also removing `autodoc_mock_imports` from sphinx configuration, required by `adafruit_esp32spi_wifimanager`'s neopixel dependency
> Remove adafruit_esp32spi_wifimanager import dependency 

- examples/adafruit_io_simpletest_analog_in.py
Adding an example of sending analog sensor data (in this case - the light sensor built-into the PyPortal) to Adafruit IO. This'll be useful for people who are building data-loggers, or projects which use analog sensors and want to send their data to Adafruit IO.
Tested on PyPortal.
> Add example: AnalogIn

- examples/adafruit_io_simpletest_data.py
- examples/adafruit_io_simpletest_digital_out.py
- examples/adafruit_io_simpletest_feeds.py
- examples/adafruit_io_simpletest_groups.py
- examples/adafruit_io_simpletest_metadata.py
- examples/adafruit_io_simpletest_randomizer.py
- examples/adafruit_io_simpletest_temperature.py
- examples/adafruit_io_simpletest_weather.py
* Removed `microcontroller` pin definitions in favor of nicer PyPortal `board.` pin names for all examples.
* Comment out ESP32 example pin setup, uncomment PyPortal.
Addressing https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/9
Tested on a PyPortal running CircuitPython 4.0.0b2 latest.
> Update examples for PyPortal board., default examples to pyportal

- adafruit_io/adafruit_io.py
- examples/adafruit_io_simpletest_analog_in.py
- examples/adafruit_io_simpletest_data.py
- examples/adafruit_io_simpletest_digital_out.py
- examples/adafruit_io_simpletest_feeds.py
- examples/adafruit_io_simpletest_groups.py
- examples/adafruit_io_simpletest_metadata.py
- examples/adafruit_io_simpletest_randomizer.py
- examples/adafruit_io_simpletest_temperature.py
- examples/adafruit_io_simpletest_weather.py
Added `precision` kwarg to `send_data` to truncate floating point values to a specified `precision` decimal places before the payload is created and sent to Adafruit IO.
Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/12
Tested with PyPortal
> Add optional precision kwarg for formatting floating point data

- README.rst
- examples/adafruit_io_simpletest_esp_at.py
* Added reference to library in README
* Added modified example for using the esp_at libary with CircuitPython_AdafruitIO
> ESP_AT Support

- README.rst
This PR should correct the build.
> Correct underlining of titles in README for rST

- adafruit_io/adafruit_io.py
Custom header encoding was fixed in ESP32SPI (https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/releases/tag/1.3.4). This PR drops explicit byte-encoding for headers.
* Append `User-Agent` for this library onto existing request headers.
* New `_create_headers` method, referenced in HTTP get/post/delete client actions
> add user-agent to http header string, remove header byte encoding

- README.rst
- examples/adafruit_io_simpletest_analog_in.py
- examples/adafruit_io_simpletest_data.py
- examples/adafruit_io_simpletest_digital_out.py
- examples/adafruit_io_simpletest_esp_at.py
- examples/adafruit_io_simpletest_feeds.py
- examples/adafruit_io_simpletest_groups.py
- examples/adafruit_io_simpletest_metadata.py
- examples/adafruit_io_simpletest_randomizer.py
- examples/adafruit_io_simpletest_temperature.py
- examples/adafruit_io_simpletest_weather.py
Changing username and key strings in `examples` to match the default IO naming within `secrets.py`: https://github.com/adafruit/Adafruit_CircuitPython_PyPortal/blob/master/adafruit_pyportal.py#L518
> Update variable names in examples for default secrets.py 

- adafruit_io/adafruit_io.py
This PR modifies the `receive_time` method to support the new time endpoint on Adafruit IO: `/integrations/time/struct.json`. This endpoint will return a time based on the IP Address.
The new `receive_time` returns the time as a `struct_time`(https://circuitpython.readthedocs.io/en/latest/shared-bindings/time/__init__.html#time.struct_time)
The previous /time endpoint returned a plaintext response, instead of json. Since the new endpoint returns a JSON response, this PR will remove the `return_text` kwarg from the HTTP `_get` method
> Add new IP-based time endpoint

- examples/adafruit_io_simpletest_analog_in.py
- examples/adafruit_io_simpletest_data.py
- examples/adafruit_io_simpletest_digital_out.py
- examples/adafruit_io_simpletest_feeds.py
- examples/adafruit_io_simpletest_groups.py
- examples/adafruit_io_simpletest_metadata.py
- examples/adafruit_io_simpletest_randomizer.py
- examples/adafruit_io_simpletest_temperature.py
- examples/adafruit_io_simpletest_weather.py
This PR proposes updating examples to `try/except` on `board.D#`. This will let examples run on boards like the PyPortal/Metro M4 without editing the example code.
Examples tested with a PyPortal and an Feather M4 + AirLift Breakout
> Update simpletest examples to detect boards with built-in ESP32

- adafruit_io/adafruit_io.py
Updating library's `IO_MQTT` class to reflect changes to MiniMQTT staged in PR https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/pull/6
> Update for minimqtt properties

- adafruit_io/adafruit_io.py
- examples/mqtt/adafruit_io_simpletest.py
Fixes https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/25
* `_on_subscribe_mqtt` and `_on_unsubscribe_mqtt` added to Adafruit IO's `MQTT_API`
* Subscribing and unsubscribing to/from feeds will now correctly execute user-defined callback methods in user-code
* MQTT Simpletest example updated for `subscribe` and `unsubscribe`.
Code Test Result:
* subscribed to feed -> `subscribe()` from code.py called
* unsubscribed from feed -> `unsubscribe()` from code.py called
* Publishing to feed does not change feed value, or call `message()` from code.
```
code.py output:
Connected to Adafruit IO!  Listening for DemoFeed changes...
Subscribed to brubell/feeds/DemoFeed with QOS level 0
Unsubscribed from brubell/feeds/DemoFeed with PID 2
Publishing a new message every 10 seconds... …
```
> Implement network callbacks for Feed Subscribe/Unsubscribe

- adafruit_io/adafruit_io.py
Properly close responses (https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/blob/master/adafruit_esp32spi/adafruit_esp32spi_requests.py#L72) from HTTP methods and return only the JSON data.
Tested with `adafruit_io_simpletest_api.py` and PyPortal (CPY 3b6)
> Ran 13 tests in 138.637 seconds
> Close HTTP method responses

- docs/conf.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_cellular.py
Adding example for using this library with an [Adafruit FONA](https://github.com/adafruit/Adafruit_CircuitPython_FONA) interface.
> Add Example for Cellular Interfaces

- adafruit_io/adafruit_io.py
satisfies #40 
As stated in the referenced issue, this lib's `loop_blocking()` will be broken upon next release of minimqtt lib. Thus I removed the method to preempt any incompatibility.
> remove loop_blocking

- examples/adafruit_io_mqtt/adafruit_io_groups.py
- examples/adafruit_io_mqtt/adafruit_io_location.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_cellular.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_eth.py
- examples/adafruit_io_mqtt/adafruit_io_time.py
- examples/adafruit_io_simpletest.py
Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/42
Examples tested on `Adafruit CircuitPython 5.3.1 on 2020-07-13; Adafruit PyPortal with samd51j20`
---
groups
```
code.py output:
Connecting to WiFi...
Connected!
Connecting to Adafruit IO...
Connected to Adafruit IO!
Publishing new messages to group feeds every 5 seconds...
Publishing value 23 to feed: weatherstation.temperature
Publishing value 92 to feed: weatherstation.humidity
Feed ['temperature'] received new value: ['23']
Publishing value 97 to feed: weatherstation.temperature
Publishing value 25 to feed: weatherstation.humidity
```
---
location
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
Connecting to WiFi...
Connected!
Connected to Adafruit …
```
> Fix Attribute Error, set_socket

- adafruit_io/adafruit_io.py
- examples/adafruit_io_mqtt/adafruit_io_feed_callback.py
Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/45
Tested on `Adafruit CircuitPython 5.3.1 on 2020-07-13; Adafruit PyPortal with samd51j20`
Test is the example modified to include `remove_callback`
Expected behavior - should not fire a second time since it's removed
```
def on_battery_msg(client, topic, message):
print("Battery level: {}v".format(message))
print("Removing feed callback...")
io.remove_feed_callback("battery")
```
Behavior: 
```
code.py output:
Connecting to WiFi...
Connected!
Connecting to Adafruit IO...
Connected to Adafruit IO!  Listening for DemoFeed changes...
Subscribed to brubell/feeds/battery with QOS level 0
Battery level: 0.15v
Removing feed callback...
Feed battery received new value: 0.42 <= OK, executed on_message instead of …
```
> Add feed callback mechanism

- examples/adafruit_io_mqtt/adafruit_io_groups.py
- examples/adafruit_io_mqtt/adafruit_io_location.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_cellular.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_eth.py
- examples/adafruit_io_mqtt/adafruit_io_time.py
- examples/adafruit_io_simpletest.py
This PR changes the  `aio_user` to `aio_username` to keep consistent with the [secrets.py](https://github.com/adafruit/circuitpython-default-files/blob/master/boards/pyportal/4.x/secrets.py#L10) file.
Currently a new maker will have a default secrets.py file with `aio_username` and this example will break.
> adafruit_io_simpletest.py: fix aio_user to aio_username

- adafruit_io/adafruit_io.py
Attempt to clarify `add_feed_callback` and `remove_feedback` functionality via docstrings, per @tannewt 's review here: https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/pull/46
> Clarify feed callback docstrings

- adafruit_io/adafruit_io.py
- adafruit_io/adafruit_io_errors.py
Messages on throttling topics now raise `AdafruitIO_ThrottleError`.
Fixes: https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/49
Tested on `Adafruit CircuitPython 6.0.0-rc.2 on 2020-11-12; Adafruit Metro M4 Airlift Lite with samd51j19`
Example Output:
```
Subscribed to brubell/throttle with QOS level 0
Publishing a new message every 10 seconds...
Publishing 26 to DemoFeed.
Publishing 38 to DemoFeed.
Publishing 25 to DemoFeed.
Publishing 67 to DemoFeed.
Publishing 79 to DemoFeed.
Publishing 92 to DemoFeed.
Publishing 22 to DemoFeed.
Publishing 2 to DemoFeed.
Publishing 33 to DemoFeed.
Publishing 45 to DemoFeed.
Publishing 92 to DemoFeed.
Publishing 64 to DemoFeed.
Publishing 15 to DemoFeed.
Traceback (most recent call last):
File "code.py", line 128, in <module>
File …
```
> Fix Throttling Message Parsing

- adafruit_io/adafruit_io.py
To be honest I don't know if this is an actual typo, but all other accesses use `{0}/feeds/{1}` so it looks like a typo.
> Fix a typo in feed argument of IO_MQTT.get method

- README.rst
- adafruit_io/adafruit_io.py
Just two typos in the __repo__ and readme
> fix URL typos

- adafruit_io/adafruit_io.py
This pull request switches `/feeds/` and `/groups/` to `/f/` and `/g/` short format to save space.
Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/56
> Switch to small feed/group format

- adafruit_io/adafruit_io.py
Adds matching function call for Create Feed in a Group Endpoint: https://io.adafruit.com/api/docs/#create-feed-in-a-group
Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/58
Tested on `Adafruit CircuitPython 6.1.0 on 2021-01-21; Adafruit PyPortal with samd51j20`
Test code:
```
print("Creating feed newfeed to group...")
io.create_feed_in_group(sensor_group["key"], "newfeed")
print("Adding feed temperature to group...")
io.add_feed_to_group(sensor_group["key"], "temperature")
```
Test result, feeds within newly created group on IO:
> Add create_feed_in_group

- README.rst
- adafruit_io/adafruit_io.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_esp32s2.py
This pull request:
* Adds a new usage example for using the library with native sockets.
* Updates library to reflect MiniMQTT release v5.0.0
* Removes redundant calls to MiniMQTT's `logger`.
Tested on `Adafruit CircuitPython 6.2.0-beta.1 on 2021-01-27; Adafruit Metro ESP32S2 with ESP32S2`.
Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/52
> Add ESP32-S2 compatibility and example

- .github/workflows/build.yml
- .pre-commit-config.yaml
- adafruit_io/adafruit_io.py
Update `_create_data` to allow metadata to be passed in as a dictionary without predefined keys.
Tested with adafruit_io_simpletest.py and adafruit_io_metadata.py examples on Feather M4 + AirLift
Related issue:
https://forums.adafruit.com/viewtopic.php?f=60&t=175772
> Update _create_data for dict. metadata

- examples/adafruit_io_mqtt/adafruit_io_pubsub_rp2040.py
Code for Pico+WiFi quickstart guide
> Add rp2040 publish/sub example for guide

- adafruit_io/adafruit_io.py
Addresses https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/issues/67
This library now performs validation for any method which access feed keys (via https://learn.adafruit.com/naming-things-in-adafruit-io/the-two-feed-identifiers):
1) The only characters we permit are lower case English letters ("a" to "z"), numbers, and dash ("-").
2) The name must be a maximum length of 128 characters.
Test case #1
`io.publish("brubell/feeds/wrongfeedkeyformat", 1)` yields:
```
Traceback (most recent call last):
File "code.py", line 94, in <module>
File "/lib/adafruit_io/adafruit_io.py", line 414, in publish
File "/lib/adafruit_io/adafruit_io.py", line 43, in validate_feed_key
TypeError: Feed key must contain lower case English letters, numbers, and dash.
```
Test case #2 …
> Validate feed key against IO naming scheme

- adafruit_io/adafruit_io.py
The recently introduced validate_feed_key [0] function
needs to account for cases when feed_id includes a
group. For example: "sign-quotes.signtext"
Fixes adafruit/Adafruit_CircuitPython_AdafruitIO#71
[0]: https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/commit/1e3d458ccbe86dade80ce3005a41ffed5d50b864
> validate feed keys used needs to allow periods

- adafruit_io/adafruit_io.py
This would allow CircuitPython to send a batch array of data to be created from all available devices to the Adafruit.IO service. I will require further testing in all of my CircuitPython devices in the coming days and will mark this for review once it is complete.
Closes #72
Reference: https://io.adafruit.com/api/docs/?python#create-multiple-data-records
> Create send_batch_data method

- adafruit_io/adafruit_io.py
I should clarify that this lets you use a forward slash or a period, not both.
> Modified regex to accept uppercase characters and a forward slash

- adafruit_io/adafruit_io.py
Currently it is not possible to subscribe to a group feed because `IO_MQTT#subscribe` validates `feed_key` unconditionally. When `group_key` is provided instead of `feed_key`, `feed_key` should not be required to be valid. This issue is also present in `IO_MQTT#unsubscribe`. 
This change makes it so that `IO_MQTT#subscribe` and `IO_MQTT#unsubscribe` validate `feed_key` and `group_key` only when one is provided.
> Allow group feeds to be subscribed to and unsubscribed from

- examples/adafruit_io_mqtt/adafruit_io_pubsub_rp2040.py
Need to explicitly call connect method after reset when WiFi manager is used with MQTT.
https://github.com/adafruit/Adafruit_CircuitPython_ESP32SPI/issues/100
> Call wifi.connect() after wifi.reset()

- adafruit_io/adafruit_io.py
- examples/adafruit_io_http/adafruit_io_create_and_get_feed.py
Adds a `create_and_get_feed` function to the library that attempts to get the feed, and if the feed does not exist, it creates and then gets the feed. Eliminates the need for the `try`/`except` in examples that try to create a feed.
Included an example of how it might be used, using the CPU temperature, which works on most CP-compatible boards.
> Add create_and_get_feed function

- setup.py
I believe this is what is causing the build failure for libraries such as https://github.com/adafruit/Adafruit_CircuitPython_PortalBase!
> Add adafruit_minimqtt as setup.py requirement

- adafruit_io/adafruit_io.py
- docs/api.rst
Missing new lines for parameters and spaces in `.. code-block`.
Fixes the display of the documentation, at least locally.
> Fix documentation of params and code blocks

- examples/adafruit_io_mqtt/adafruit_io_feed_callback.py
- examples/adafruit_io_mqtt/adafruit_io_groups.py
- examples/adafruit_io_mqtt/adafruit_io_location.py
- examples/adafruit_io_mqtt/adafruit_io_pubsub_rp2040.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_cellular.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_esp32s2.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_eth.py
- examples/adafruit_io_mqtt/adafruit_io_time.py
- examples/adafruit_io_simpletest.py
without port=1883 the board is not able to connect to Adafruit IO
> added "port" to MQTT examples

- optional_requirements.txt
- requirements.txt
- setup.py
The library does not need ESP32SPI, it works on native wifi too.
The format used for the minimqtt requirement makes it listed in "external_dependencies" instead of "dependencies" in the bundle's json file. It might be what is tripping the project bundler for the learn guides using adafruit_io, or indirectly via portalbase. At least that's my assumption.
`adafruit_minimqtt` is missing from the Project Bundle there for example:
- https://learn.adafruit.com/magtag-weather/project-code
- https://learn.adafruit.com/pyportal-weather-station/code-pyportal-with-circuitpython
> Change requirements to pypi format, remove ESP32SPI requirement

- adafruit_io/adafruit_io.py
```python
#
```
Fixes #100
I have run the pre-commit and had no issues. There are no tests so I don't know any issues. Feel free to ask for any changes.
> Added with statement for requests[Issue #100]

- adafruit_io/adafruit_io.py
> Add TypeHints to adafruit_io.py

- examples/adafruit_io_mqtt/adafruit_io_simpletest_esp32s2.py
Tested on Adafruit Feather ESP32-S2 Reverse TFT with CPY 8.2.4.
Paul Cutler raised an issue in discord about using SSL and miniMQTT with the IO library, and I realised I hadn't retested with SSL in circuitpython for a while especially since Root cert updates. The version Paul was using was 8.2.2 which has an SSL issue connecting to api.github.com so advised to update to latest CPY of 8.2.4 to get up to date root certs.
This brings the demo for the esp32s2 up to scratch, working with secrets.py or settings.toml, and optionally connecting to wifi. The port is also changed and is_ssl=True to enable SSL.
> Update for settings.toml (CPY8) and SSL.

- adafruit_io/adafruit_io.py
Hi,
Thank you for approving my PR, it's my first ever and I am happy that I have added helpful functionality.
Unfortuately, upon reviewing the docs, I found some omissions that now are corrected in this PR:
receive_n_data - [Link to Docs](https://docs.circuitpython.org/projects/adafruitio/en/latest/api.html#adafruit_io.adafruit_io.IO_HTTP.receive_n_data)
- Parameter description for n_values was missing, this has been added.
- Wording changes to specify "most recent n" to remove any ambiguity
validate_n_values - [Link to docs](https://docs.circuitpython.org/projects/adafruitio/en/latest/api.html#adafruit_io.adafruit_io.validate_n_values)
- Removed line breaks for better formatting in docs.
Thanks
> Corrections to receive_n_data documentation

- examples/adafruit_io_http/adafruit_io_groups.py
User feedback (support issue) was:
> Running a bit of the sample code from [https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/blob/main/examples/adafruit_io_http/adafruit_io_groups.py](https://github.com/adafruit/Adafruit_CircuitPython_AdafruitIO/blob/main/examples/adafruit_io_http/adafruit_io_groups.py)
> I get this error:
> `Adafruit IO Error 404: not found - API documentation can be found at `[https://io.adafruit.com/api/docs](https://io.adafruit.com/api/docs)
> It seems that the API call `add_feed_to_group(..)` is not working
It appears the code has changed since the example was written and there is a newer "create_feed_in_group" method.
It's also the case that the `add_feed_to_group` method always required an existing feed (at least according to the comments in code). …
> Highlight usage of different methods for group feeds + cleanup multigroup feeds

- adafruit_io/adafruit_io.py
- examples/adafruit_io_mqtt/adafruit_io_feed_callback.py
- examples/adafruit_io_mqtt/adafruit_io_groups.py
- examples/adafruit_io_mqtt/adafruit_io_location.py
- examples/adafruit_io_mqtt/adafruit_io_pubsub_rp2040.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_cellular.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_esp32s2.py
- examples/adafruit_io_mqtt/adafruit_io_simpletest_eth.py
- examples/adafruit_io_mqtt/adafruit_io_time.py
- examples/adafruit_io_simpletest.py
Adds callback method for on_publish, and updates examples to use it.
Fixes #122
Needs retesting on monday, marking draft until then
> Add missing "on_publish" event callback in the class IO_MQTT - adafruit_io.py

- adafruit_io/adafruit_io.py
- examples/adafruit_io_http/adafruit_io_groups.py
Fixes #97
@brentru as mentioned in discord, I had a quick look at this while in the codebase, and this seemed reasonable. I also fixed the path for send_batch_data. That then lead me to poke my nose in and test batch method (requiring `from collection import namedtuples`), I'll leave that for now
> IO_HTTP: Support creating group data with `send_group_data`

- .pylintrc
- adafruit_io/adafruit_io.py
- examples/adafruit_io_http/adafruit_io_user_info.py
Adds two new methods related to returning the current users info. One for the complete user info, and one just for the throttle/auth/sms rates+limits
Return User Usage Limits / Current Usage towards Throttle Limits with `receive_user_rate_info`
Return full account info with `receive_user_info`
Fixes #126
> Add Current User info methods
